Vagrant.configure("2") do |config|
  config.disksize.size = '40GB'
  config.vm.provision "shell", privileged: true, path: "./setup.sh"
  config.vm.define "node1" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "node1"
  vb.vm.network "private_network", ip: "192.168.33.21"
  vb.vm.box = "centos/72"
  end

  config.vm.define "node2" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "node2"
  vb.vm.network :private_network, ip: "192.168.33.22"
  vb.vm.box = "centos/72"
  end

  config.vm.define "node3" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "node3"
  vb.vm.network :private_network, ip: "192.168.33.23"
  vb.vm.box = "centos/72"
  end

  config.vm.define "node4" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "node4"
  vb.vm.network :private_network, ip: "192.168.33.24"
  vb.vm.box = "centos/72"
  end

  config.vm.define "node5" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "node5"
  vb.vm.network :private_network, ip: "192.168.33.25"
  vb.vm.box = "centos/72"
  end

  config.vm.define "node6" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "node6"
  vb.vm.network :private_network, ip: "192.168.33.26"
  vb.vm.box = "centos/72"
  end
end

