---
- name: "Disable swap"
  shell: swapoff -a

- name: "Remove swapfile from /etc/fstab"
  mount:
    name: "swap"
    fstype: sqap
    state: absent

- name: "modprobe Modules"
  shell: "modprobe {{ item }}"
  loop:
  - "ip_conntrack"
  - "br_netfilter"

- name: "Modify sysctl"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - {name: 'kernel.sysrq',value: '1' }
    - {name: 'vm.swappiness ',value: ' 0' }
    - {name: 'net.ipv4.ip_forward',value: '1' }
    - {name: 'net.ipv4.neigh.default.gc_stale_time',value: '120' }
    - {name: 'net.ipv4.conf.all.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.arp_announce ',value: ' 2' }
    - {name: 'net.ipv4.conf.lo.arp_announce',value: '2' }
    - {name: 'net.ipv4.conf.all.arp_announce',value: '2' }
    - {name: 'net.ipv4.tcp_max_tw_buckets',value: '5000' }
    - {name: 'net.ipv4.tcp_syncookies ',value: ' 1' }
    - {name: 'net.ipv4.tcp_max_syn_backlog ',value: ' 1024' }
    - {name: 'net.ipv4.tcp_synack_retries ',value: ' 2' }
    - {name: 'net.ipv4.tcp_fin_timeout',value: '30' }
    - {name: 'net.ipv4.ip_local_port_range',value: '20000 60999' }
    - {name: 'net.netfilter.nf_conntrack_max',value: '2310720' }
    - {name: 'net.bridge.bridge-nf-call-iptables',value: '1' }
    - {name: 'net.bridge.bridge-nf-call-ip6tables',value: '1' }
