---
- name: copy hbase-site.xml
  template:
    src: hbase-site.xml
    dest: /etc/hbase/conf/
    backup: yes

- name: copy hbase-env.sh
  template:
    src: hbase-env.sh
    dest: /etc/hbase/conf/
    backup: yes

- name: Create a directory if it does not exist
  file:
    path: /opt/hbase-data
    state: directory
    mode: '0755'
    owner: hbase
    group: hbase


- name: Execute the hbase-master.
  shell: /bin/bash /etc/init.d/hbase-master start 

- name: Execute the hbase-regionserver.
  shell: /bin/bash /etc/init.d/hbase-regionserver start
