---
- name: copy docker.repo
  template:
    src: docker.repo
    dest: /etc/yum.repos.d/

- name: This command will reset yum cache.
  shell:
    cmd: yum clean all && yum makecache


- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    disablerepo: "ftp"
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes

# - name: download docker images 
#   get_url:
#     url: "ftp://ftp/pub/docker-images"
#     dest: "{{ oracle_path }}"
#     force: yes

- name: import docker image
  shell:
    cmd: docker load < registry.tar
