--- 
- name: "Create a directory if it does not exist"
  file:
    path: /etc/yum.repos.d/bak
    state: directory
    mode: '0755'

- name: "Move *.repo to bak"
  shell: 
    cmd: mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak

- name: "copy ftp.repo"
  copy:
    src: ftp.repo
    dest: /etc/yum.repos.d/

- name: "This command will reset yum cache"
  shell:
    cmd: yum clean all && yum makecache

- name: "Install base application"
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - 'vim'
    - 'bash-completion'
    - 'chrony'
    - 'kmod'

- name: "Set chrony"
  template:
    src: "chrony.conf"
    dest: "/etc/chrony.conf"
  notify:
    - restart chrony