---
- name: yum config
  hosts: all
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /etc/yum.repos.d/bak
        state: directory
        mode: '0755'

    - name: copy hosts
      copy:
        src: hosts.txt
        dest: /etc/hosts
        backup: yes

    - name: copy ftp.repo
      copy:
        src: ftp.repo
        dest: /etc/mine.conf

    - name: This command will reset yum cache.
      shell:
        cmd: yum clean all && yum makecache

    - name: install vim
      yum:
        name: vim

- name: jdk install
  hosts: all
  tasks:
    - name: copy install_jdk.sh
      copy:
        src: install_jdk.sh
        dest: /root/install_jdk.sh

    - name: Run a script install jdk
      script: /bin/bash /root/install_jdk.sh

- name: bigdata install
  hosts: zookeeper
  tasks:
    - name: install zookeeper
      yum:
        name: zookeeper

    - name: install zookeeper-server
      yum:
        name: zookeeper-server

    - name: copy install_jdk.sh
      copy:
        src: zoo.cfg
        dest: /etc/zookeeper/conf/zoo.cfg
        backup: yes

    - name: copy zookeeper_myid_set.sh
      copy:
        src: zookeeper_myid_set.sh
        dest: /root/zookeeper_myid_set.sh

    - name: Run zookeeper_myid_set.sh
      shell: /bin/bash /root/zookeeper_myid_set.sh

    - name: copy zookeeper.service
      copy:
        src: zookeeper.service
        dest: /usr/lib/systemd/system/zookeeper.service

    - name: enable and start zookeeper
      systemd:
        name: zookeeper
        state: started
        enabled: yes



