Vagrant.configure("2") do |config|
  config.disksize.size = '40GB'
  config.vm.provision "shell", privileged: true, path: "./setup.sh"
  config.vm.define "k8s-master" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "k8s-master"
  vb.vm.network "private_network", ip: "192.168.33.60"
  vb.vm.box = "centos/72"
  end

  config.vm.define "k8s-node1" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "k8s-node1"
  vb.vm.network :private_network, ip: "192.168.33.61"
  vb.vm.box = "centos/72"
  end

  config.vm.define "k8s-node2" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "k8s-node2"
  vb.vm.network :private_network, ip: "192.168.33.62"
  vb.vm.box = "centos/72"
  end

end

