- name: "Disable selinux"
  selinux:
    state: disabled

- name: "Stop firewalld"
  systemd:
    name: firewalld
    enabled: no
    state: stopped

- name: "Set timezone"
  timezone:
    name: Asia/Shanghai

- name: "copy base packages"
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
  loop:
  - chrony-2.1.1-3.el7.centos.x86_64.rpm
  - vsftpd-3.0.2-10.el7.x86_64.rpm


- name: "Install base packages"
  shell:
    cmd: "rpm -ih /root/{{ item }}"
  loop:
  - "chrony-2.1.1-3.el7.centos.x86_64.rpm"
  - "vsftpd-3.0.2-10.el7.x86_64.rpm"

- name: "Set chrony"
  copy:
    src: "chrony.conf"
    dest: "/etc/chrony.conf"
  notify:
    - restart chrony

- name: "start and enable vsftpd"
  systemd:
    name: vsftpd
    enabled: yes
    state: started

- name: "copy resource"
  shell:
    cmd: cp -r /ansible/resource/{{ item }} /var/ftp/pub/
  loop:
  - createrepo
  - docker
  - docker-images
  - gitlab
  - kernel
  - kubernetes
  - nslookup
  - packages
  - tcpdump

- name: Create a directory if it does not exist
  file:
    path: /etc/yum.repos.d/bak
    state: directory
    mode: '0755'

- name: Move *.repo to bak
  shell: 
    cmd: mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak

- name: copy hosts
  copy:
    src: hosts.txt
    dest: /etc/hosts
    backup: yes

- name: copy ftp.repo
  copy:
    src: ftp.repo
    dest: /etc/yum.repos.d/

- name: This command will reset yum cache.
  shell:
    cmd: yum clean all && yum makecache

- name: "Install base application"
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - 'vim'
    - 'bash-completion'
    - 'createrepo'

- name: copy hostsname_set.sh
  copy:
    src: hostsname_set.sh
    dest: /root/

- name: This command will reset hostsname.
  shell:
    cmd: /bin/bash /root/hostsname_set.sh

- name: "Set ssh"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: "UseDNS", line: "UseDNS no" }
    - { regexp: "ClientAliveInterval", line: "ClientAliveInterval 600" }
    - { regexp: "ClientAliveCountMax", line: "ClientAliveCountMax 2" }
    - { regexp: "AddressFamily", line: "AddressFamily inet" }
    - { regexp: "PermitRootLogin", line: "PermitRootLogin yes" }
    - { regexp: "PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "PasswordAuthentication", line: "PasswordAuthentication no" }
  notify:
    - restart sshd