---
images_path: "/home"

script: 
- hostsname_set.sh
- parted.sh

ftp_packages:
- createrepo
- docker
- docker-images
- gitlab
- kernel
- kubernetes
- nslookup
- packages
- tcpdump
- harbor
- helm

packages:
- docker-ce 
- docker-ce-cli 
- containerd.io

master_images:
- kube-proxy                  
- kube-apiserver              
- kube-controller-manager     
- kube-scheduler              
- etcd                        
- coredns                     
- pause
- flannel
- dashboard
- metrics-scraper 

node_images:
- flannel
- kube-proxy
- pause
- dashboard
- metrics-scraper 

gitlab_ip: "192.168.33.40"

registry_ip: "192.168.33.50"

dns_ip: "192.168.33.50"

ntp_ip: "192.168.33.20"

k8s_master_ip: "192.168.33.60"

local_images: "registry.example.com"

dns_configs:
- resolv.dnsmasq
- dnsmasq.conf
- add_hosts

k8s_version: "1.20.0"