---
images_path: "/home"

packages:
- docker-ce 
- docker-ce-cli 
- containerd.io

images:
- registry
- dnsmasq

master_images:
- kube-proxy                  
- kube-apiserver              
- kube-controller-manager     
- kube-scheduler              
- etcd                        
- coredns                     
- pause
- flannel
- dashboard
- metrics-scraper 

node_images:
- flannel
- kube-proxy
- pause
- dashboard
- metrics-scraper 

gitlab_ip: "192.168.33.40"

registry_ip: "192.168.33.50"

ntp_ip: "192.168.33.20"

k8s_master_ip: "192.168.33.60"

local_images: "registry.example.com"

configs:
- resolv.dnsmasq
- dnsmasq.conf
- add_hosts

k8s_version: "1.20.0"