apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tomcat
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/pv
    server: {{ k8s_master_ip }}