Vagrant.configure("2") do |config|
  
  config.vm.define "hbase-master1" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "hbase-master1"
  vb.vm.network "private_network", ip: "192.168.33.21"
  vb.vm.box = "centos/72"
  end

  config.vm.define "hbase-master2" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "hbase-master2"
  vb.vm.network :private_network, ip: "192.168.33.22"
  vb.vm.box = "centos/72"
  end

  config.vm.define "hbase-master3" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "hbase-master3"
  vb.vm.network :private_network, ip: "192.168.33.23"
  vb.vm.box = "centos/72"
  end

  config.vm.define "hbase-master4" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "hbase-master4"
  vb.vm.network :private_network, ip: "192.168.33.24"
  vb.vm.box = "centos/72"
  end

  config.vm.define "hbase-master5" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "hbase-master5"
  vb.vm.network :private_network, ip: "192.168.33.5"
  vb.vm.box = "centos/72"
  end

  config.vm.define "hbase-master6" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "hbase-master6"
  vb.vm.network :private_network, ip: "192.168.33.26"
  vb.vm.box = "centos/72"
  end
end
