Vagrant.configure("2") do |config|
  config.disksize.size = '50GB'
  config.vm.define "docker-registry" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
    end
  vb.vm.host_name = "docker-registry"
  vb.vm.network "private_network", ip: "192.168.33.50"
  vb.vm.box = "centos/72"
  config.vm.provision "shell", privileged: true, path: "./setup.sh"
  end
end

